#!/bin/bash
# Generate The Environment File Used By The Project
# shellcheck disable=SC2154

cat << EOF > ./.env
# ---------------------------------------------------------------------------------------
# Generated by Project Setup Script - Don't Edit This Unless You Know What You Are Doing!
# ---------------------------------------------------------------------------------------

# Docker Version To Build Into Development Image - Sourced From The Host System
DOCKER_VERSION=$(docker version --format '{{.Server.Version}}')
DOCKER_COMPOSE_VERSION=$(docker-compose version | head -n1 | grep -Eo "[0-9]\.[0-9]{1,2}(\.[0-9]{1,2})?")

# Set The Docker Group Id To The Docker Group Id On The Host
DOCKER_GROUP_ID=$(getent group docker | cut -d":" -f 3)

# Hadolint Latest Version - Sourced From Online Repository
HADOLINT_VERSION=$(curl -s -v https://github.com/hadolint/hadolint/releases/latest 2>&1 | grep "location:" | grep -Eo "v[0-9]{1,2}\.[0-9]{1,2}(\.[0-9]{1,2})?")

# Shell Check Latest Version - Sourced From Online Repository
SHELLCHECK_VERSION=$(curl -s -v https://github.com/koalaman/shellcheck/releases/latest 2>&1 | grep "location:" | grep -Eo "v[0-9]{1,2}\.[0-9]{1,2}(\.[0-9]{1,2})?")

PROJECTS_ROOT_DIR=$(cd .. ; echo "${PWD}")

# Current User Id And Group Id
USER_GROUP_ID=$(id -g)
USER_USER_ID=$(id -u)

# AWS Configuration Path
USER_HOME_PATH=${HOME}
EOF
